- name: Target Machine Setup (Windows) - Elastic Agent Only
  hosts: target_windows
  become: yes
  become_method: runas
  vars:
    elastic_agent_version: "9.1.5"
    insecure: true

  vars_files:
    - ../../logging/linux/.fleet_credentials.yml

  tasks:
    - name: Verify Fleet credentials are loaded
      assert:
        that:
          - fleet_url is defined
          - fleet_enrollment_token is defined
        fail_msg: |
          Fleet credentials not found! Ensure logging server playbook has run and ../../logging/linux/.fleet_credentials.yml exists.

    - name: Copy Elastic Agent ZIP from controller (offline)
      win_copy:
        src: "{{ playbook_dir }}\\..\\..\\downloads\\elastic-agent-{{ elastic_agent_version }}-windows-x86_64.zip"
        dest: "C:\\Users\\Public\\Downloads\\ElasticAgent.zip"

    - name: Unzip Elastic Agent
      win_unzip:
        src: "C:\\Users\\Public\\Downloads\\ElasticAgent.zip"
        dest: "C:"
        delete_archive: yes

    - name: Install Elastic Agent with enrollment token
      win_command: >-
        C:\\elastic-agent-{{ elastic_agent_version }}-windows-x86_64\\elastic-agent.exe install
        --url "{{ fleet_url }}"
        --enrollment-token "{{ fleet_enrollment_token }}"
        --insecure
      args:
        chdir: "C:\\elastic-agent-{{ elastic_agent_version }}-windows-x86_64"

    - name: Check Elastic Agent status (Windows)
      win_command: C:\\Elastic\\Agent\\elastic-agent.exe status
      register: win_agent_status
      ignore_errors: yes

    - debug:
        msg: "Elastic Agent install output:\n{{ win_agent_status.stdout }}\nView agents in Kibana: {{ kibana_host }}/app/fleet/agents"