- name: Target Machine Setup (Linux) - Elastic Agent Only
  hosts: target_linux
  become: yes
  vars:
    elastic_agent_version: "8.17.0"
    insecure: true

  vars_files:
    - ../../logging/.fleet_credentials.yml

  tasks:
    - name: Verify Fleet credentials are loaded
      assert:
        that:
          - fleet_url is defined
          - fleet_enrollment_token is defined
        fail_msg: |
          Fleet credentials not found! Ensure logging server playbook has run and ../../logging/.fleet_credentials.yml exists.

    - name: Ensure target downloads directory exists on controller
      file:
        path: "{{ playbook_dir }}/downloads"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Download Elastic Agent tarball to controller (for offline target)
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
        dest: "{{ playbook_dir }}/downloads/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
        mode: '0644'
        timeout: 600
      delegate_to: localhost
      run_once: true

    - name: Copy Elastic Agent TAR from controller to target
      copy:
        src: "{{ playbook_dir }}/downloads/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/elastic-agent.tar.gz"
        mode: '0644'

    - name: Extract Elastic Agent on target
      unarchive:
        src: "/tmp/elastic-agent.tar.gz"
        dest: "/opt/elastic-agent-{{ elastic_agent_version }}-linux-x86_64"
        remote_src: yes

    - name: Install Elastic Agent
      shell: |
        cd /opt/elastic-agent-{{ elastic_agent_version }}-linux-x86_64
        ./elastic-agent install --non-interactive
      args:
        creates: /opt/Elastic/Agent/elastic-agent
      register: install_output
      async: 300
      poll: 10
      failed_when: install_output.rc not in [0, 2]

    - name: Start/Restart Elastic Agent service
      systemd:
        name: elastic-agent
        state: restarted
        enabled: yes

    - name: Force enroll Elastic Agent to Fleet
      shell: |
        /opt/Elastic/Agent/elastic-agent enroll \
          --url={{ fleet_url }} \
          --enrollment-token={{ fleet_enrollment_token }} \
          {% if insecure %}--insecure{% endif %} \
          --force \
          --non-interactive
      register: enroll_result
      async: 300
      poll: 10
      failed_when: enroll_result.rc not in [0]

    - name: Restart Elastic Agent service after enrollment
      systemd:
        name: elastic-agent
        state: restarted
        enabled: yes

    - name: Wait for agent to stabilize and download policies
      pause:
        seconds: 45
        prompt: "Waiting for Fleet policies (including Endpoint) to download..."

    - name: Check agent status
      shell: /opt/Elastic/Agent/elastic-agent status 2>&1
      register: agent_status_detailed
      changed_when: false
      failed_when: false

    - name: Check agent inspect (shows integrations)
      shell: /opt/Elastic/Agent/elastic-agent inspect 2>&1
      register: agent_inspect
      changed_when: false
      failed_when: false

    - name: Check what policies are assigned in Fleet
      uri:
        url: "{{ kibana_host }}/api/fleet/agents"
        method: GET
        user: "{{ elastic_username }}"
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        headers:
          kbn-xsrf: "true"
        status_code: [200, 401, 404]
        return_content: yes
      register: fleet_agents_check
      failed_when: false
      delegate_to: localhost

    - name: Check Default Agent Policy configuration
      uri:
        url: "{{ kibana_host }}/api/fleet/agent_policies/default-policy"
        method: GET
        user: "{{ elastic_username }}"
        password: "{{ elastic_password }}"
        force_basic_auth: yes
        headers:
          kbn-xsrf: "true"
        status_code: [200, 401, 404]
        return_content: yes
      register: default_policy_check
      failed_when: false
      delegate_to: localhost
