---
################################################################################
# TARGET MACHINE SETUP - ELASTIC AGENT DEPLOYMENT
################################################################################
#
# Purpose:
#   This playbook deploys Elastic Agent to target machines for security
#   monitoring and log collection. Agents automatically enroll with the
#   Fleet Server and begin sending data to the logging server.
#
# What gets collected:
#   - System logs (syslog, auth logs, etc.)
#   - Process events (executions, network connections)
#   - File changes and integrity monitoring
#   - Network traffic metadata
#   - Security events (authentication, privilege escalation)
#
# Architecture:
#   Target Machine (This playbook)
#   └── Elastic Agent
#       ├── Enrolls with Fleet Server (port 8220)
#       ├── Receives policy from Fleet
#       ├── Collects logs and metrics
#       └── Sends data to Elasticsearch
#
# Prerequisites:
#   - Linux machine (Ubuntu/Debian or RHEL/CentOS)
#   - Minimum 512MB RAM, 1 CPU core
#   - Network connectivity to Fleet Server (port 8220)
#   - SSH access with sudo privileges
#   - Python 3 installed on target
#   - Logging server must be deployed first!
#
# Credentials:
#   This playbook automatically reads credentials from:
#   ../../.fleet_credentials.yml
#   
#   This file is generated by the logging server playbook and contains:
#   - Fleet Server URL
#   - Enrollment token
#   - Elasticsearch/Kibana URLs
#
# Usage:
#   1. Ensure logging server is deployed first
#   2. Update target_linux.ini with your target machine IPs
#   3. Run: ansible-playbook -i target_linux.ini main.yml
#   4. Agents will automatically enroll and appear in Kibana Fleet UI
#
# Verification:
#   - Check Kibana → Management → Fleet → Agents
#   - Verify agent shows as "Healthy"
#   - Check Kibana → Discover for incoming logs
#
# Estimated Runtime: 3-5 minutes per machine
#
################################################################################

- name: Target Machine Setup (Linux) - Elastic Agent Only
  hosts: target_linux
  become: yes
  vars:
    elastic_agent_version: "8.17.0"
    insecure: true

  vars_files:
    - ../../logging/.fleet_credentials.yml

  tasks:
    - name: Verify Fleet credentials are loaded
      assert:
        that:
          - fleet_url is defined
          - fleet_enrollment_token is defined
        fail_msg: |
          Fleet credentials not found! Ensure logging server playbook has run and ../../logging/linux/.fleet_credentials.yml exists.

    - name: Copy Elastic Agent TAR from controller (offline)
      copy:
        src: "{{ playbook_dir }}/../../logging/downloads/elastic-agent-{{ elastic_agent_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/elastic-agent.tar.gz"
        mode: '0644'

    - name: Extract Elastic Agent
      unarchive:
        src: "/tmp/elastic-agent.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Install Elastic Agent and enroll to Fleet
      shell: |
        cd /opt/elastic-agent-{{ elastic_agent_version }}-linux-x86_64
        ./elastic-agent install \
          --url={{ fleet_url }} \
          --enrollment-token={{ fleet_enrollment_token }} \
          {% if insecure %}--insecure{% endif %} \
          --non-interactive
      args:
        creates: /opt/Elastic/Agent/elastic-agent

    - name: Check Elastic Agent status
      shell: /opt/Elastic/Agent/elastic-agent status || true
      register: agent_status
      ignore_errors: yes

    - name: Show agent install output
      debug:
        msg: "Elastic Agent status:\n{{ agent_status.stdout }}\nView agents in Kibana: {{ kibana_host }}/app/fleet/agents"

################################################################################
# POST-DEPLOYMENT NOTES
################################################################################
#
# What's Running:
# └── Elastic Agent (systemd service: elastic-agent)
#     ├── Enrolled with Fleet Server
#     ├── Collecting system logs
#     ├── Monitoring processes and network
#     └── Sending data to Elasticsearch
#
# Verification Steps:
# 1. Check agent status on target machine:
#    sudo elastic-agent status
#
# 2. View logs if troubleshooting needed:
#    sudo journalctl -u elastic-agent -f
#
# 3. In Kibana, go to: Management → Fleet → Agents
#    - Agent should appear with "Healthy" status
#    - Click agent name to see details and logs
#
# 4. View collected data: Kibana → Discover
#    - Select data view: logs-*
#    - Filter by host.name: <this-machine>
#
# Agent Management:
# - Uninstall: sudo elastic-agent uninstall
# - Restart: sudo systemctl restart elastic-agent
# - Status: sudo elastic-agent status
# - Logs: sudo journalctl -u elastic-agent
#
# What Data is Collected (Default Policy):
# ├── System Logs
# │   ├── /var/log/syslog
# │   ├── /var/log/auth.log
# │   └── /var/log/messages
# ├── System Metrics
# │   ├── CPU, Memory, Disk usage
# │   └── Network interface statistics
# └── Security Events (if auditd is installed)
#     ├── File access attempts
#     ├── User authentication events
#     └── Process executions
#
# Customizing Data Collection:
# 1. In Kibana, go to: Management → Fleet → Agent policies
# 2. Click the policy assigned to this agent
# 3. Add integrations for additional data sources:
#    - Auditd (Linux security events)
#    - File Integrity Monitoring
#    - Network Packet Capture
#    - Custom log files
#    - Application-specific logs
#
# Troubleshooting:
# - Agent not appearing in Fleet?
#   → Check network connectivity to port 8220
#   → Verify enrollment token is valid
#   → Check agent logs: sudo elastic-agent logs
#
# - Agent shows "Offline"?
#   → Check if service is running: systemctl status elastic-agent
#   → Verify Fleet Server is accessible
#   → Check firewall rules
#
# - No data appearing in Elasticsearch?
#   → Verify agent policy is assigned
#   → Check agent components: elastic-agent status
#   → Look for errors in: sudo elastic-agent logs
#
################################################################################
